export const PLAYER_TYPES = {
  BATSMAN: "BATSMAN",
  BOWLER: "BOWLER",
  ALL_ROUNDER: "ALL_ROUNDER",
};

export const MATCH_FORMATS = {
  ODI: "ODI",
  TEST: "TEST",
  T20: "T20",
};

export const MATCH_STATUS = {
  LIVE: "LIVE",
  NOT_STARTED: "NOT_STARTED",
  COMPLETED: "COMPLETED",
  ABANDONED: "ABANDONED",
  NO_RESULT: "NO_RESULT",
};
