import { QueryClientProvider } from "@/provider/query-client";
import { Roboto } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";
import Footer from "./shared/Footer";
import Header from "./shared/Header";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "CricBex",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <QueryClientProvider>
          <NuqsAdapter>
            <Header />
            <main>{children}</main>
            <Footer />
          </NuqsAdapter>
        </QueryClientProvider>
      </body>
    </html>
  );
}
